#!/usr/bin/perl

# *.trg парсер - парсит все *.trg из каталога откуда он 
# запущен и сохраняет полученный результат в файл _purge_result.txt
use locale;
use POSIX qw (locale_h);
setlocale(LC_CTYPE, 'ru_RU.KOI8-R');
$file_name=undef;
@files=();
opendir(DIR, ".");
	foreach $file_name (readdir(DIR)) {
		push @files, $file_name if $file_name =~ m/[0-9]+\.trg/;
	}
closedir(DIR);

if (@files) {
	open RES, ">_purge_result.txt";
	print RES "Generated by $0\n";
	foreach $file_name (@files) {
		open TRG, $file_name;
		$writen_file_name=0;
		
		$wrt=0;
		
		while ($line=<TRG>) {
			if ($line =~ m/^(#\d+)$/) {
				$trig_vnum = $1;
				$wrt = 1;
				$writen_trig_vnum=0
			};
			$line =~ s/^(.+)?\~$/\1/;
			$trig_name = $line if $wrt == 2;
			if ($wrt>4 && 
			      ($line =~ m/^.*?[wmo\%]purge\%?[ ]+[^\%]+$/ ||
			       $line =~ m/^.*?[wmo\%]purge\%?[ ]+\%\w+?\.name\%.*$/)
			    ) {
				if (!$writen_file_name) {
					print RES "\nFile : ".$file_name."\n";$writen_file_name=1;
				};
				if (!$writen_trig_vnum) {
					print RES $trig_vnum." название: ".$trig_name;$writen_trig_vnum=1;
				};
				print RES $line;
			}
			$wrt++ if $wrt;
		}
		
		close TRG;
	}
	close RES;
}
